default: &default
  adapter: mysql2
  port: 3306
  pool: 5
  timeout: 5000
  encoding: utf8
  locale: <%= ENV['LANG'] %>
  host: db

development:
  <<: *default
  adapter: mysql2
  port: 3306
  encoding: utf8
  database: resound_dev
  username: <%= ENV['whoami'] %>
  host: localhost

test:
  <<: *default
  database: resound_test
  username: <%= ENV['whoami'] %>
  host: localhost

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PW'] %>
  host: <%= ENV['DB_HOST'] %>
