default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  locale: en_US.utf8
  host: db
  port: 5432

development:
  <<: *default
  database: resound_dev
  username: postgres

test:
  <<: *default
  database: resound_test
  username: louise.yang

production:
  <<: *default
  database: resound
  username: postgres

