default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  locale: <%= ENV['LANG'] %>
  host: db
  port: 5432

development:
  <<: *default
  database: resound_dev
  username: <%= ENV['whoami'] %>
  host: localhost

test:
  <<: *default
  database: resound_test
  username: <%= ENV['whoami'] %>
  host: localhost

production:
  <<: *default
  database: resound
  username: postgres

